
import { GoogleGenerativeAI } from '@google/generative-ai'

// Initialize GenAI
const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY || '')

export interface AIAnalysisRequest {
    transactions: any[]
    query?: string // Optional user query for specific insights
}

export interface AIAnalysisResponse {
    insight: string
    disclaimer: string
}

const SYSTEM_PROMPT = `
You are PayAware AI, a helpful financial assistant.
Your goal is to provide neutral, non-advisory insights based strictly on the provided transaction data.
rules:
1. DO NOT provide financial advice, investment recommendations, or predict future market trends.
2. DO NOT judge the user's spending habits (e.g., don't say "You spend too much on X").
3. DO stick to factual summaries and observations (e.g., "Your highest expense this month is X").
4. ALWAYS include a disclaimer that this is for informational purposes only.
5. If the data is empty, say so.
`

export async function generateInsight(data: AIAnalysisRequest): Promise<AIAnalysisResponse> {
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

    // Graceful degradation if no key
    if (!process.env.GOOGLE_AI_API_KEY) {
        return {
            insight: "AI Insights are currently in demo mode. (Configure GOOGLE_AI_API_KEY to enable real insights). Based on your data, you have logged transactions. Please review your dashboard for details.",
            disclaimer: "This is a simulated response."
        }
    }

    const prompt = `
    ${SYSTEM_PROMPT}
    
    User Query (if any): ${data.query || 'General overview'}
    
    Transaction Data JSON:
    ${JSON.stringify(data.transactions.slice(0, 50))} -- Limit to 50 for context window safety
  `

    try {
        const result = await model.generateContent(prompt)
        const response = await result.response
        const text = response.text()

        return {
            insight: text,
            disclaimer: "Generated by AI. Not Financial Advice."
        }
    } catch (error: any) {
        console.error("AI Generation Error:", error)

        let errorMessage = "Unable to generate insights at this moment."

        if (error.status === 429 || error.message?.includes('429') || error.message?.includes('Resource has been exhausted')) {
            errorMessage = "AI Quota exceeded. Please try again later."
        }

        return {
            insight: errorMessage,
            disclaimer: "System Error"
        }
    }
}
